version: "3.9"

services:

  #setup postgres db
  postgres:
    image: postgres:16.3
    restart: always
    shm_size: 128mb
    env_file: ./config/.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
