networks:
  default:
    name: hcu-model-builder-network

services:
  # hcu-model-builder-backend:
  #   image: hcu-model-builder-backend
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   env_file: ./config/.env
  #   ports:
  #     - "3030:3030"
  #   networks:
  #     default:
  #       aliases:
  #         - backend

  #setup postgres db
  postgres:
    image: postgres:16.3
    restart: always
    shm_size: 128mb
    env_file: ./config/.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./scripts/postgres-init/init-keycloak-db.sh:/docker-entrypoint-initdb.d/init-keycloak-db.sh
      - ./scripts/postgres-init/init-keycloak-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
    networks:
      default:
        aliases:
          - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      default:
        aliases:
          - adminer

  keyycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    restart: always
    env_file: ./config/.env
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres/keycloak"
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      #KC_LOG_LEVEL: debug

    command: ["start-dev"]
    ports:
      - 8081:8080
    depends_on:
      - postgres
    networks:
      default:
        aliases:
          - keycloak
