networks:
  default:
    name: hcu-model-builder-network

services:
  hcu-model-builder-backend:
    image: hcu-model-builder-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file: ./config/.env
    ports:
      - "3030:3030"
    networks:
      default:
        aliases:
          - backend

  #setup postgres db
  postgres:
    image: postgres:16.3
    restart: always
    shm_size: 128mb
    env_file: ./config/.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./scripts/postgres-init/init-keycloak-db.sh:/docker-entrypoint-initdb.d/init-keycloak-db.sh
      - ./scripts/postgres-init/init-keycloak-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
    networks:
      default:
        aliases:
          - postgres
  redis:
    image: redis:7.0.5
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      default:
        aliases:
          - redis
