# Creating multi-stage build for production
FROM node:20.18.3-alpine3.20 AS builder
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/
COPY hcu-urban-model-builder-backend/migrations ./migrations
COPY hcu-urban-model-builder-backend/config ./config
COPY hcu-urban-model-builder-backend/ts-node.register.mjs ./ts-node.register.mjs
COPY hcu-urban-model-builder-backend/knexfile.ts ./knexfile.ts
COPY hcu-urban-model-builder-backend/package*.json ./
COPY hcu-urban-model-builder-backend/tsconfig.json ./

RUN npm config set fetch-retry-maxtimeout 600000 -g && npm install

CMD [ "npm", "run", "migrate" ]
