export const unitsCollection = [
  {
    Unitless: null,
  },
  {
    'Distance, Area and Volume': {
      Metric: [
        'Millimeters',
        'Centimeters',
        'Meters',
        'Kilometers',
        'Square Millimeters',
        'Square Centimeters',
        'Square Meters',
        'Hectares',
        'Square Kilometers',
        'Cubic Millimeters',
        'Cubic Centimeters',
        'Liters',
        'Cubic Meters',
      ],
      English: [
        'Inches',
        'Feet',
        'Yards',
        'Miles',
        'Square Inches',
        'Square Feet',
        'Square Yards',
        'Acres',
        'Square Miles',
        'Fluid Ounces',
        'Quarts',
        'Gallons',
        'Acre Feet',
      ],
    },
  },
  {
    'Velocity, Acceleration and Flow': {
      Metric: [
        'Meters per Second',
        'Meters per Second Squared',
        'Kilometers per Hour',
        'Kilometers per Hour Squared',
        'Liters per Second',
        'Cubic Meters per Second',
        'Kilograms per Second',
      ],
      English: [
        'Feet per Second',
        'Feet per Second Squared',
        'Miles per Hour',
        'Miles per Hour Squared',
        'Gallons per Second',
        'Gallons per Minute',
        'Pounds per Second',
      ],
    },
  },
  {
    'Mass, Force and Pressure': {
      Metric: [
        'Milligrams',
        'Grams',
        'Kilograms',
        'Tonnes',
        'Newtons',
        'Pascals',
        'Kilopascals',
        'Bars',
        'Atmospheres',
      ],
      English: [
        'Ounces',
        'Pounds',
        'Tons',
        'Pounds Force',
        'Pounds per Square Inch',
      ],
    },
  },
  {
    'Temperature and Energy': {
      Metric: [
        'Degrees Celsius',
        'Degrees Kelvin',
        'Joules',
        'Kilojoules',
        'Watts',
        'Kilowatts',
        'Megawatts',
        'Gigawatts',
        'Amperes',
        'Millivolts',
        'Volts',
        'Kilovolts',
        'Coulombs',
        'Farads',
      ],
      English: [
        'Degrees Fahrenheit',
        'Calories',
        'Kilocalories',
        'British Thermal Units',
      ],
    },
  },
  {
    Time: [
      'Milliseconds',
      'Seconds',
      'Minutes',
      'Hours',
      'Days',
      'Weeks',
      'Months',
      'Quarters',
      'Years',
    ],
  },
  {
    Money: {
      Dollars: [
        'Dollars',
        'Dollars per Second',
        'Dollars per Hour',
        'Dollars per Day',
        'Dollars per Week',
        'Dollars per Month',
        'Dollars per Quarter',
        'Dollars per Year',
      ],
      Euros: [
        'Euros',
        'Euros per Second',
        'Euros per Hour',
        'Euros per Day',
        'Euros per Week',
        'Euros per Month',
        'Euros per Quarter',
        'Euros per Year',
      ],
    },
  },
  {
    'Business and Commerce': [
      'People',
      'Customers',
      'Employees',
      'Workers',
      'Factories',
      'Buildings',
      'Units',
      'Widgets',
      'Parts',
    ],
  },
  {
    'Ecology and Nature': [
      'Individuals',
      'Animals',
      'Plants',
      'Trees',
      'Biomass',
      'Chemistry',
      'Atoms',
      'Molecules',
      'Moles',
    ],
  },
];
