import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowDownAZ,
  faBook,
  faCalendarPlus,
  faCaretDown,
  faChevronDown,
  faCircleCheck,
  faCirclePlay,
  faCircleQuestion,
  faCode,
  faCodeCommit,
  faDownload,
  faEye,
  faGlobe,
  faLaptopCode,
  faPause,
  faPencil,
  faPlay,
  faPlus,
  faPowerOff,
  faRemove,
  faRightToBracket,
  faSearch,
  faShield,
  faSpinner,
  faTimes,
  faTrash,
  faUser,
  faUserTag,
} from '@fortawesome/free-solid-svg-icons';

export function initialize(): void {
  library.add(
    faArrowDownAZ,
    faBook,
    faCalendarPlus,
    faCaretDown,
    faChevronDown,
    faCircleCheck,
    faCirclePlay,
    faCircleQuestion,
    faCode,
    faCodeCommit,
    faDownload,
    faEye,
    faGlobe,
    faLaptopCode,
    faPause,
    faPencil,
    faPlay,
    faPlus,
    faPowerOff,
    faRemove,
    faRightToBracket,
    faSearch,
    faShield,
    faSpinner,
    faTimes,
    faTrash,
    faUser,
    faUserTag,
  );
}

export default {
  initialize,
};
