name: deploy-book

on:
  push:
    branches:
    - documentation

#defaults:
#  run:
#    working-directory: ./docs

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm

    - name: Install dependencies
      run: npm ci
      working-directory: ./docs

    - name: Build website
      run: npm build
      working-directory: ./docs

    - name: Upload Build Artifact
      uses: actions/upload-pages-artifact@v3
      working-directory: ./docs
      with:
        path: build

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4